-- Resettable Supabase schema for Mi Clase.
-- This is intended for the current learning/test app. It drops app tables first.

drop table if exists public.homework_files cascade;
drop table if exists public.homework cascade;
drop table if exists public.vocabulary cascade;
drop table if exists public.notes cascade;
drop table if exists public.quiz_words cascade;
drop table if exists public.quizzes cascade;
drop table if exists public.classes cascade;

create table public.classes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  class_date date not null,
  created_at timestamptz not null default now()
);

create table public.notes (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade unique,
  content text not null default '',
  updated_at timestamptz not null default now()
);

create table public.vocabulary (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  spanish_word text not null,
  english_translation text not null default '',
  created_at timestamptz not null default now()
);

create table public.homework (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null default '',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table public.homework_files (
  id bigint generated by default as identity primary key,
  homework_id bigint not null references public.homework(id) on delete cascade,
  filename text not null,
  object_key text not null,
  created_at timestamptz not null default now()
);

create table public.quizzes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null default 'Untitled Quiz',
  last_score_correct integer,
  last_score_total integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quiz_words (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  spanish_word text not null,
  english_translation text not null default '',
  created_at timestamptz not null default now()
);

create index classes_user_id_idx on public.classes(user_id);
create index classes_class_date_idx on public.classes(class_date desc);
create index vocabulary_class_id_idx on public.vocabulary(class_id);
create index homework_class_id_idx on public.homework(class_id);
create index homework_files_homework_id_idx on public.homework_files(homework_id);
create index quizzes_user_id_idx on public.quizzes(user_id);
create index quiz_words_quiz_id_idx on public.quiz_words(quiz_id);

alter table public.classes enable row level security;
alter table public.notes enable row level security;
alter table public.vocabulary enable row level security;
alter table public.homework enable row level security;
alter table public.homework_files enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_words enable row level security;

grant usage on schema public to authenticated;
grant all on public.classes to authenticated;
grant all on public.notes to authenticated;
grant all on public.vocabulary to authenticated;
grant all on public.homework to authenticated;
grant all on public.homework_files to authenticated;
grant all on public.quizzes to authenticated;
grant all on public.quiz_words to authenticated;

create policy "Users can manage their classes"
on public.classes
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Users can manage notes for their classes"
on public.notes
for all
to authenticated
using (
  exists (
    select 1 from public.classes
    where classes.id = notes.class_id
      and classes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.classes
    where classes.id = notes.class_id
      and classes.user_id = auth.uid()
  )
);

create policy "Users can manage vocabulary for their classes"
on public.vocabulary
for all
to authenticated
using (
  exists (
    select 1 from public.classes
    where classes.id = vocabulary.class_id
      and classes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.classes
    where classes.id = vocabulary.class_id
      and classes.user_id = auth.uid()
  )
);

create policy "Users can manage homework for their classes"
on public.homework
for all
to authenticated
using (
  exists (
    select 1 from public.classes
    where classes.id = homework.class_id
      and classes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.classes
    where classes.id = homework.class_id
      and classes.user_id = auth.uid()
  )
);

create policy "Users can manage files for their homework"
on public.homework_files
for all
to authenticated
using (
  exists (
    select 1
    from public.homework
    join public.classes on classes.id = homework.class_id
    where homework.id = homework_files.homework_id
      and classes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.homework
    join public.classes on classes.id = homework.class_id
    where homework.id = homework_files.homework_id
      and classes.user_id = auth.uid()
  )
);

create policy "Users can manage their quizzes"
on public.quizzes
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Users can manage words for their quizzes"
on public.quiz_words
for all
to authenticated
using (
  exists (
    select 1 from public.quizzes
    where quizzes.id = quiz_words.quiz_id
      and quizzes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.quizzes
    where quizzes.id = quiz_words.quiz_id
      and quizzes.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('homework-files', 'homework-files', false)
on conflict (id) do nothing;

create policy "Users can read their homework files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'homework-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can upload their homework files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'homework-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can update their homework files"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'homework-files'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'homework-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can delete their homework files"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'homework-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);
