{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mi-clase.fullname" . }}
  labels:
    {{- include "mi-clase.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.tls.mode "auto" }}
    {{- if eq .Values.tls.certManager.issuerKind "ClusterIssuer" }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.certManager.issuerName }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.tls.certManager.issuerName }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.tls.mode }}
  tls:
    - secretName: {{ .Values.tls.secretName }}
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mi-clase.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
