apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mi-clase.fullname" . }}
  labels:
    {{- include "mi-clase.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s"
    (include "mi-clase.postgresqlUsername" .)
    (include "mi-clase.postgresqlPassword" .)
    (include "mi-clase.postgresqlHost" .)
    (include "mi-clase.postgresqlPort" .)
    (include "mi-clase.postgresqlDatabase" .) | quote }}
  REDIS_URL: {{ if (include "mi-clase.redisPassword" .) | trim -}}
    {{ printf "redis://:%s@%s:%s"
      (include "mi-clase.redisPassword" .)
      (include "mi-clase.redisHost" .)
      (include "mi-clase.redisPort" .) | quote }}
  {{- else -}}
    {{ printf "redis://%s:%s"
      (include "mi-clase.redisHost" .)
      (include "mi-clase.redisPort" .) | quote }}
  {{- end }}
  MINIO_ACCESS_KEY: {{ include "mi-clase.minioAccessKey" . | quote }}
  MINIO_SECRET_KEY: {{ include "mi-clase.minioSecretKey" . | quote }}
  {{- if .Values.libretranslate.apiKey }}
  LIBRE_TRANSLATE_API_KEY: {{ .Values.libretranslate.apiKey | quote }}
  {{- end }}
