apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: mi-clase
spec:
  version: "3.0.0-beta-1+k8s-1.34"
  extensions:
    helmCharts:
      - chart:
          name: cert-manager
          chartVersion: "v1.20.2"
        releaseName: cert-manager
        namespace: cert-manager
        weight: -1
        values:
          crds:
            enabled: true

      - chart:
          name: traefik
          chartVersion: "39.0.7"
        releaseName: traefik
        namespace: traefik
        values:
          service:
            type: NodePort
          ports:
            web:
              nodePort: 30080
            websecure:
              nodePort: 30443
