apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: mi-clase
spec:
  title: Mi Clase
  icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MTIiIGhlaWdodD0iNTEyIiB2aWV3Qm94PSIwIDAgMjU2IDI1NiI+PHBhdGggZD0iTTE2OCA0MC41OFYzMmEyNCAyNCAwIDAgMC0yNC0yNGgtMzJhMjQgMjQgMCAwIDAtMjQgMjR2OC41OEE1Ni4wOSA1Ni4wOSAwIDAgMCA0MCA5NnYxMjBhMTYgMTYgMCAwIDAgMTYgMTZoMTQ0YTE2IDE2IDAgMCAwIDE2LTE2Vjk2YTU2LjA5IDU2LjA5IDAgMCAwLTQ4LTU1LjQyWk0xMTIgMjRoMzJhOCA4IDAgMCAxIDggOHY4aC00OHYtOGE4IDggMCAwIDEgOC04Wm01NiAxMzZIODh2LThhOCA4IDAgMCAxIDgtOGg2NGE4IDggMCAwIDEgOCA4Wm0tODAgMTZoNDh2OGE4IDggMCAwIDAgMTYgMHYtOGgxNnY0MEg4OFptMTEyIDQwaC0xNnYtNjRhMjQgMjQgMCAwIDAtMjQtMjRIOTZhMjQgMjQgMCAwIDAtMjQgMjR2NjRINTZWOTZhNDAgNDAgMCAwIDEgNDAtNDBoNjRhNDAgNDAgMCAwIDEgNDAgNDB2MTIwWk0xNTIgODhhOCA4IDAgMCAxLTggOGgtMzJhOCA4IDAgMCAxIDAtMTZoMzJhOCA4IDAgMCAxIDggOFoiLz48L3N2Zz4=
  statusInformers:
    - deployment/mi-clase-mi-clase
    - statefulset/mi-clase-postgresql
    - statefulset/mi-clase-redis-master
    - statefulset/mi-clase-minio
