# HelmChart custom resource
apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: samplechart
spec:
  chart:
    name: mi-clase
    chartVersion: 0.4.0

  releaseName: mi-clase
  namespace: mi-clase

  values:
    features:
      quizzesEnabled: 'repl{{ LicenseFieldValue "quiz_feature" }}'