# HelmChart custom resource
apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: mi-clase
spec:
  chart:
    name: mi-clase
    chartVersion: 0.4.0

  releaseName: mi-clase
  namespace: mi-clase

  values:
    image:
      repository: 'repl{{ ReplicatedImageName (HelmValue ".image.repository") }}'

    replicated:
      image:
        registry: 'repl{{ ReplicatedImageRegistry (HelmValue ".replicated.image.registry") }}'

    postgresql:
      image:
        registry: 'repl{{ ReplicatedImageRegistry (HelmValue ".postgresql.image.registry") }}'

    redis:
      image:
        registry: 'repl{{ ReplicatedImageRegistry (HelmValue ".redis.image.registry") }}'

    minio:
      image:
        repository: 'repl{{ ReplicatedImageName (HelmValue ".minio.image.repository") }}'
      mcImage:
        repository: 'repl{{ ReplicatedImageName (HelmValue ".minio.mcImage.repository") }}'

    libretranslate:
      image:
        repository: 'repl{{ ReplicatedImageName (HelmValue ".libretranslate.image.repository") }}'

    service:
      type: ClusterIP

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: repl{{ ConfigOption "hostname" }}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - repl{{ ConfigOption "hostname" }}
          secretName: mi-clase-tls

    tls:
      mode: 'repl{{ ConfigOption "tls_mode" }}'
      secretName: mi-clase-tls
      certManager:
        issuerKind: ClusterIssuer
        issuerName: letsencrypt-prod
        email: 'repl{{ ConfigOption "acme_email" }}'

    certManager:
      install: false
      createIssuer: repl{{ ConfigOptionEquals "tls_mode" "auto" }}

    ingressController:
      enabled: false

    features:
      quizzesEnabled: 'repl{{ LicenseFieldValue "quiz_feature" }}'

  builder:
    postgresql:
      enabled: true
    redis:
      enabled: true
    minio:
      enabled: true
    libretranslate:
      enabled: true
    ingressController:
      enabled: false
    certManager:
      install: false